### ISSUE TITLE
Compare PDF with password protection

### ISSUE THREAD

**Issue by xaviercwy** [vslavik/diff-pdf#37] opened 2016-04-27 02:22 UTC
I tried to use diff-pdf to compare a list of PDF inside folders.
Some files are protected by password and some does not.
Diff-pdf works fine for those without protection.
For comparing password protected PDF, I found no output PDF or any message.

1. Is it possible to compare PDF with password protection?
2. If no, any notification or log generated in this case?

My testing environment is Win7 x64 Enterprise SP1
Cheers

**Comment by vslavik** [comment] 2016-04-27 17:25
Please see this project’s description: if you’re not a developer willing to implement fixes yourself, diff-pdf is not meant for you.

Also, duplicate of #23 in all likelihood.

**Closed by vslavik** 2016-04-27 17:25 UTC
